namespace Aoc2024.Test;

public class Day6Tests
{
    [Fact]
    public void Part1()
    {
        const string input = """
                             ....#.....
                             .........#
                             ..........
                             ..#.......
                             .......#..
                             ..........
                             .#..^.....
                             ........#.
                             #.........
                             ......#...
                             """;
        var day = new Day6(input);
        const string expected = "41";
        var actual = day.Part1();
        actual.Should().Be(expected);
    }

    [Fact]
    public void Part2()
    {
        const string input = """
                             ....#.....
                             .........#
                             ..........
                             ..#.......
                             .......#..
                             ..........
                             .#..^.....
                             ........#.
                             #.........
                             ......#...
                             """;
        var day = new Day6(input);
        const string expected = "6";
        var actual = day.Part2();
        actual.Should().Be(expected);
    }
}