namespace Aoc2024.Test;

public class Day8Tests
{
    [Fact]
    public void Part1()
    {
        const string input = """
                             ............
                             ........0...
                             .....0......
                             .......0....
                             ....0.......
                             ......A.....
                             ............
                             ............
                             ........A...
                             .........A..
                             ............
                             ............
                             """;
        var day = new Day8(input);
        const string expected = "14";
        var actual = day.Part1();
        actual.Should().Be(expected);
    }

    [Fact]
    public void Part2()
    {
        const string input = """
                             ............
                             ........0...
                             .....0......
                             .......0....
                             ....0.......
                             ......A.....
                             ............
                             ............
                             ........A...
                             .........A..
                             ............
                             ............
                             """;
        var day = new Day8(input);
        const string expected = "34";
        var actual = day.Part2();
        actual.Should().Be(expected);
    }
}